### ISSUE TITLE
Datastore support for Events

### ISSUE THREAD

**Issue by dhgarrette** [mrios730/Team-25#48]
Create two new methods:
* `Datastore.storeEvent(Event)`
* `Datastore.getAllEvents()`

**Comment by mojuwara** [comment]
Sorry, Janny. I didn't see this and already made a getAllEvents() method in the Datastore on my branch to retrieve events for the event page. If you've already done the method as well, I'll just delete mine and merge with yours when it's ready.

**Comment by jhuang09** [comment]
No worries, Mo! I haven't gotten to that function yet, so it's totally okay :). Thanks for doing it!
